/*-
 * Copyright (c) 2016 Hiroki Mori
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * $FreeBSD$
 */

#ifndef	_ARM_M83XXXREG_H
#define	_ARM_M83XXXREG_H

#define	COMCERTO_APB_TIMER_BASE				0x10050000

#define	COMCERTO_TIMER0_HIGH_BOUND			0x0000
#define	COMCERTO_TIMER0_CURRENT_COUNT			0x0004
#define	COMCERTO_TIMER1_HIGH_BOUND			0x0008
#define	COMCERTO_TIMER1_CURRENT_COUNT			0x000c
#define	COMCERTO_TIMER2_LOW_BOUND			0x0010
#define	COMCERTO_TIMER2_HIGH_BOUND			0x0014
#define	COMCERTO_TIMER2_CTRL				0x0018
#define	COMCERTO_TIMER2_CURRENT_COUNT			0x001c
#define	COMCERTO_TIMER3_LOW_BOUND			0x0020
#define	COMCERTO_TIMER3_HIGH_BOUND			0x0024
#define	COMCERTO_TIMER3_CTRL				0x0028
#define	COMCERTO_TIMER3_CURRENT_COUNT			0x002c
#define	COMCERTO_TIMER4_HIGH_BOUND			0x0030
#define	COMCERTO_TIMER4_CURRENT_COUNT			0x0034
#define	COMCERTO_TIMER5_LOW_BOUND			0x0038
#define	COMCERTO_TIMER5_HIGH_BOUND			0x003c
#define	COMCERTO_TIMER5_CURRENT_COUNT			0x0040
#define	COMCERTO_TIMER5_CTRL				0x0044
#define	COMCERTO_TIMER_IRQ_MASK				0x0048
#define	COMCERTO_TIMER_STATUS				0x0050
#define	COMCERTO_TIMER_STATUS_CLR			0x0050
#define	COMCERTO_TIMER_WDT_HIGH_BOUND			0x00d0
#define	COMCERTO_TIMER_WDT_CONTROL			0x00d4
#define	COMCERTO_TIMER_WDT_CURRENT_COUNT		0x00d8

#define	COMCERTO_TIMER0					0x0001
#define	COMCERTO_TIMER1					0x0002
#define	COMCERTO_TIMER2					0x0004
#define	COMCERTO_TIMER3					0x0008
#define	COMCERTO_TIMER4					0x0010
#define	COMCERTO_TIMER5					0x0020

#define	COMCERTO_INTC_STATUS_REG_0			0x0000
#define	COMCERTO_INTC_SET_STATUS_REG_0			0x0004
#define	COMCERTO_INTC_ARM0_IRQMASK_0			0x0008
#define	COMCERTO_INTC_ARM0_FIQMASK_0			0x000c
#define	COMCERTO_INTC_ARM1_IRQMASK_0			0x0010
#define	COMCERTO_INTC_ARM1_FIQMASK_0			0x0014
#define	COMCERTO_INTC_ARM1_CONTROL_REG			0x0018
#define	COMCERTO_INTC_IRQ_ACK_TEST_REG			0x001c
#define	COMCERTO_INTC_STATUS_REG_1			0x0020
#define	COMCERTO_INTC_SET_STATUS_REG_1			0x0024
#define	COMCERTO_INTC_ARM0_IRQMASK_1			0x0028
#define	COMCERTO_INTC_ARM0_FIQMASK_1			0x002c
#define	COMCERTO_INTC_ARM1_IRQMASK_1			0x0030
#define	COMCERTO_INTC_ARM1_FIQMASK_1			0x0034
#define	COMCERTO_INTC_STATUS_MASK_REG_1			0x0038
#define	COMCERTO_INTC_ARM0_IRQ_WNR			0x0060

#define	COMCERTO_APB_GPIO_BASE				0x10070000
#define	COMCERTO_GPIO_OUTPUT_REG			0x00
#define	COMCERTO_GPIO_OE_REG				0x04
#define	COMCERTO_GPIO_HI_INT_ENABLE_REG			0x08
#define	COMCERTO_GPIO_LO_INT_ENABLE_REG			0x0c
#define	COMCERTO_GPIO_INPUT_REG				0x10

#define	COMCERTO_APB_CLK_BASE				0x100b0000
#define	COMCERTO_CLK_CLK_PWR_DWN			0x40
#define	COMCERTO_BLOCK_RESET_REG			0x100

#define	COMCERTO_AHB_DDR_BASE				0x80000000

#endif	/* _ARM_M83XXXREG_H */
